apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ui-scaler
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Values.services.ui.name }}
  targetCPUUtilizationPercentage: {{ .Values.services.targetCPUPercentage }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: product-api-scaler
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Values.services.productApi.name }}
  targetCPUUtilizationPercentage: {{ .Values.services.targetCPUPercentage }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: order-api-scaler
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Values.services.orderApi.name }}
  targetCPUUtilizationPercentage: {{ .Values.services.targetCPUPercentage }}
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: gateway-scaler
spec:
  minReplicas: 1
  maxReplicas: 3
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: {{ .Values.services.gateway.name }}
  targetCPUUtilizationPercentage: {{ .Values.services.targetCPUPercentage }}