kind: Service
apiVersion: v1
metadata:
  name: rvstore-ui
spec:
  type: NodePort
  selector:
    app: ui
  ports:
  - protocol: TCP
    port: {{ .Values.services.ui.port }}
    nodePort: {{ .Values.services.ui.nodePort }}
---
kind: Service
apiVersion: v1
metadata:
  name: rvstore-product-api
spec:
  type: ClusterIP
  selector:
    app: product-api
  ports:
  - protocol: TCP
    port: {{ .Values.services.productApi.port }}

---
kind: Service
apiVersion: v1
metadata:
  name: rvstore-order-api
spec:
  type: ClusterIP
  selector:
    app: order-api
  ports:
  - protocol: TCP
    port: {{ .Values.services.orderApi.port }}

---
kind: Service
apiVersion: v1
metadata:
  name: rvstore-orders-mongodb
spec:
  type: ClusterIP
  selector:
    app: order-mongodb
  ports:
  - protocol: TCP
    port: {{ .Values.mongo.port }}

---
kind: Service
apiVersion: v1
metadata:
  name: rvstore-api-gateway
spec:
  type: NodePort
  selector:
    app: api-gateway
  ports:
  - protocol: TCP
    port: {{ .Values.services.gateway.port }}
    nodePort: {{ .Values.services.gateway.nodePort }}
