apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
  labels:
    app: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - name: ui
        image: vergeops/k8s-rvstore-ui:1.0
        imagePullPolicy: Always
        ports:
        - name: ui-port
          containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: ui-port
        readinessProbe:
          httpGet:
            path: /
            port: ui-port
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /
            port: health-port
          periodSeconds: 10
          failureThreshold: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api-deployment
  labels:
    app: product-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
    spec:
      containers:
      - name: rvstore-product-api
        image: vergeops/k8s-rvstore-product-api:1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: workload-config
        ports:
        - name: product-port
          containerPort: 9001
        livenessProbe:
          httpGet:
            path: /products/
            port: product-port
        readinessProbe:
          httpGet:
            path: /products/
            port: product-port
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /products/
            port: product-port
          periodSeconds: 10
          failureThreshold: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api-deployment
  labels:
    app: auth-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
      - name: rvstore-auth-api
        image: vergeops/k8s-rvstore-auth-api:1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: workload-config
        ports:
        - name: auth-port
          containerPort: 9003
        livenessProbe:
          httpGet:
            path: /auth/login
            port: auth-port
        readinessProbe:
          httpGet:
            path: /auth/login
            port: auth-port
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /auth/login
            port: auth-port
          periodSeconds: 10
          failureThreshold: 5
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api-deployment
  labels:
    app: order-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
      - name: rvstore-order-api
        image: vergeops/k8s-rvstore-order-api:1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: workload-config
        ports:
        - name: order-port
          containerPort: 9002
        livenessProbe:
          httpGet:
            path: /orders
            port: order-port
        readinessProbe:
          httpGet:
            path: /orders
            port: order-port
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /orders
            port: order-port
          periodSeconds: 10
          failureThreshold: 5

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-simulator-deployment
  labels:
    app: order-simulator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-simulator
  template:
    metadata:
      labels:
        app: order-simulator
    spec:
      containers:
      - name: rvstore-order-simulator
        image: vergeops/k8s-rvstore-order-simulator:1.0
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: workload-config

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: rvstore-api-gateway
        image: vergeops/k8s-rvstore-api-gateway:1.0
        imagePullPolicy: Always
        ports:
        - name: gw-port
          containerPort: 9000
        envFrom:
        - configMapRef:
            name: workload-config
        livenessProbe:
          httpGet:
            path: /health
            port: gw-port
        readinessProbe:
          httpGet:
            path: /health
            port: gw-port
          periodSeconds: 10
          successThreshold: 2
          failureThreshold: 1
        startupProbe:
          httpGet:
            path: /health
            port: gw-port
          periodSeconds: 10
          failureThreshold: 5
